### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by bkchr** [swarmer/mig#4]
Hi, what is the status of the project? Is the implementation finished or is something missing? I'm currently searching an implementation of Quic in rust.

**Comment by swarmer** [comment]
Hi @bkchr, sorry for the late reply. This was for a university project and I'm working on different things now (even though this project was super fun).

It's pretty functional as a transport protocol and even has some nice unusual properties like supporting migration of an endpoint to a new ip, and handling high random packet loss much much better than stock TCP.

But, though my intent was to implement as much QUIC as I could, a lot is missing. In particular:
- No encryption at all
- It's "QUIC" in the sense that it uses QUIC packet format from a spring 2017 draft. But the packets changed even when I stopped working on this, and now I think they've changed even more.
- No congestion control
- Doesn't go over 8mbit/s (because my flow control, implemented in like a few hours, is shit, I think)

Let me know if you have any questions or if I can help with something.

**Comment by bkchr** [comment]
Okay, thank you for your long explanation :)

I'm already working on binding a c library, to get something working.

**Comment by swarmer** [comment]
Okay, good luck with your binding! Maybe I'll use it myself some day.
